//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DocumentIndexEntities : DbContext
    {
        public DocumentIndexEntities()
            : base("name=DocumentIndexEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NodeIndex> NodeIndex { get; set; }
        public virtual DbSet<WordPosition> WordPosition { get; set; }
        public virtual DbSet<DocumentMetadata> DocumentMetadata { get; set; }
    }
}
