//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSS
{
    using System;
    using System.Collections.Generic;
    
    public partial class WordPosition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WordPosition()
        {
            this.NodeIndex = new HashSet<NodeIndex>();
            this.WordPosition1 = new HashSet<WordPosition>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DocumentIndex { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<int> NextPosition { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NodeIndex> NodeIndex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WordPosition> WordPosition1 { get; set; }
        public virtual WordPosition WordPosition2 { get; set; }
    }
}
